name: Update README with Action Metadata
description: Update README with action metadata.
author: 'Robert Lindley'

branding:
  color: 'green'
  icon: 'book'

inputs:
  readme-file-path:
    description: "The path to the README file. Defaults to 'README.md'."
    required: false
    default: 'README.md'

  action-yaml-path:
    description:
      The path to the action's YAML configuration file. This defaults to
      'action.yml'.
    required: true
    default: 'action.yml'

runs:
  using: 'node20'
  main: './dist/index.js'
