author: 'Robert Lindley'
name: Update README.md with Action Metadata
description:
  Updates a README.md file with metadata from an action's YAML configuration
  file. This includes information such as the action name, description, inputs,
  outputs, and other relevant details.

branding:
  color: 'green'
  icon: 'book'

inputs:
  readme-file-path:
    description:
      The path to the README.md file that should be updated. This is relative to
      the repository root. If not specified, it defaults to 'README.md'.
    required: true
    default: './README.md'

  action-file-path:
    description:
      The path to the YAML configuration file for the action. This is relative
      to the repository root. If not specified, it defaults to 'action.yml'.
    required: true
    default: './action.yml'

  action-repository:
    description:
      The repository where the action is located. This is used to generate links
      and references within the README.md file.
    required: false
    default: '${{ github.action_repository }}'

outputs: {}
runs:
  using: 'node20'
  main: './dist/index.mjs'
