author: 'Robert Lindley'
name: Update README with Action Metadata
description:
  Updates a README.md file with metadata from an action's YAML configuration
  file. This includes information such as the action name, description, inputs,
  outputs, and other relevant details. This ensures that the README is always
  up-to-date with the latest information about the action.

branding:
  color: 'green'
  icon: 'book'

inputs:
  readme-file-path:
    description:
      The path to the README.md file that should be updated. This is relative to
      the repository root. If not specified, it defaults to 'README.md'.
    required: false
    default: 'README.md'

  action-yaml-path:
    description:
      The path to the YAML configuration file for the action. This is relative
      to the repository root. If not specified, it defaults to 'action.yml'.
    required: false
    default: 'action.yml'

runs:
  using: 'node20'
  main: './dist/index.mjs'
