name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Style Check
        id: npm-format-check
        run: npm run format:check

      - name: Lint Check
        id: npm-lint
        run: npm run lint

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ${{ github.workspace }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_STANDARD: false

      - name: Unit Tests
        id: npm-ci-test
        run: npm run ci-test

  integration-test:
    name: Integration Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4

      - name: Integration Test
        id: test-action
        uses: ./
        with:
          action-yaml-path: ./action.yml
