name: Create SBOM

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  SBOM-upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4

      - name: Generate SBOM
        # generation command documentation: https://github.com/microsoft/sbom-tool#sbom-generation
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn $ -pv 1.0.0 -ps coderrob -nsb https://coderrob.com -V Verbose

      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
