name: Update README

on:
  workflow_dispatch:
  push:
    paths: |
      ./action.yml
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        uses: coderrob/update-action-readme@main
        with:
          action-file-path: ./action.yml
          readme-file-path: ./README.md

      - name: Upload README
        uses: actions/upload-artifact@v4
        with:
          name: Update Readme with latest version of the action.
          path: ./README.md
